spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000
      connection-test-query: SELECT 1

  application:
    name: spring-security-demo
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

